import type { StrapiApp } from '@strapi/strapi/admin';

export default {
  config: {
    locales: ['ru'],
    translations: {
      ru: {
        // === Content Manager: Content Types ===
        // api::actor.actor — Актёр
        'content-manager.content-types.api::actor.actor.info.displayName': 'Актёры',
        'content-manager.content-types.api::actor.actor.fields.name': 'Имя',
        'content-manager.content-types.api::actor.actor.fields.slug': 'URL (слаг)',
        'content-manager.content-types.api::actor.actor.fields.photo': 'Фото',
        'content-manager.content-types.api::actor.actor.fields.role': 'Роль',
        'content-manager.content-types.api::actor.actor.fields.rank': 'Должность',
        'content-manager.content-types.api::actor.actor.fields.bio': 'О себе',
        'content-manager.content-types.api::actor.actor.fields.roles': 'Роли',
        'content-manager.content-types.api::actor.actor.fields.gallery': 'Галерея',
        // api::contact.contact — Контакты
        'content-manager.content-types.api::contact.contact.info.displayName': 'Контакты',
        'content-manager.content-types.api::contact.contact.fields.address': 'Адрес',
        'content-manager.content-types.api::contact.contact.fields.boxOffice': 'Касса',
        'content-manager.content-types.api::contact.contact.fields.admin': 'Администрация',
        'content-manager.content-types.api::contact.contact.fields.press': 'Пресс-служба',
        'content-manager.content-types.api::contact.contact.fields.emailBoxOffice': 'Email кассы',
        'content-manager.content-types.api::contact.contact.fields.emailAdmin': 'Email администрации',
        'content-manager.content-types.api::contact.contact.fields.emailPress': 'Email пресс-службы',
        'content-manager.content-types.api::contact.contact.fields.socialVk': 'ВКонтакте',
        'content-manager.content-types.api::contact.contact.fields.socialTelegram': 'Telegram',
        'content-manager.content-types.api::contact.contact.fields.socialInstagram': 'Instagram',
        'content-manager.content-types.api::contact.contact.fields.workingHoursBoxOffice': 'Часы работы кассы',
        'content-manager.content-types.api::contact.contact.fields.workingHoursAdmin': 'Часы работы администрации',
        'content-manager.content-types.api::contact.contact.fields.mapEmbed': 'Код карты',
        'content-manager.content-types.api::contact.contact.fields.howToGetThere': 'Как добраться',
        'content-manager.content-types.api::contact.contact.fields.footerTagline': 'Слоган в подвале',
        'content-manager.content-types.api::contact.contact.fields.footerContactsTitle': 'Заголовок контактов в подвале',
        'content-manager.content-types.api::contact.contact.fields.footerCopyright': 'Авторские права (без года)',

        // api::hero-slide.hero-slide — Слайд героя
        'content-manager.content-types.api::hero-slide.hero-slide.info.displayName': 'Слайды героя',
        'content-manager.content-types.api::hero-slide.hero-slide.fields.title': 'Заголовок',
        'content-manager.content-types.api::hero-slide.hero-slide.fields.subtitle': 'Подзаголовок',
        'content-manager.content-types.api::hero-slide.hero-slide.fields.image': 'Изображение',
        'content-manager.content-types.api::hero-slide.hero-slide.fields.cta': 'Текст кнопки',
        'content-manager.content-types.api::hero-slide.hero-slide.fields.ctaHref': 'Ссылка кнопки',
        'content-manager.content-types.api::hero-slide.hero-slide.fields.order': 'Порядок',

        // api::news-item.news-item — Новость / Событие
        'content-manager.content-types.api::news-item.news-item.info.displayName': 'Новости и события',
        'content-manager.content-types.api::news-item.news-item.fields.slug': 'URL (слаг)',
        'content-manager.content-types.api::news-item.news-item.fields.title': 'Заголовок',
        'content-manager.content-types.api::news-item.news-item.fields.excerpt': 'Краткое описание',
        'content-manager.content-types.api::news-item.news-item.fields.image': 'Изображение',
        'content-manager.content-types.api::news-item.news-item.fields.date': 'Дата',
        'content-manager.content-types.api::news-item.news-item.fields.category': 'Категория',
        'content-manager.content-types.api::news-item.news-item.fields.content': 'Полный текст',

        // api::performance.performance — Спектакль
        'content-manager.content-types.api::performance.performance.info.displayName': 'Спектакли',
        'content-manager.content-types.api::performance.performance.fields.title': 'Название',
        'content-manager.content-types.api::performance.performance.fields.slug': 'URL (слаг)',
        'content-manager.content-types.api::performance.performance.fields.poster': 'Постер',
        'content-manager.content-types.api::performance.performance.fields.gallery': 'Галерея',
        'content-manager.content-types.api::performance.performance.fields.subtitle': 'Подзаголовок',
        'content-manager.content-types.api::performance.performance.fields.author': 'Автор',
        'content-manager.content-types.api::performance.performance.fields.director': 'Режиссёр',
        'content-manager.content-types.api::performance.performance.fields.directorQuote': 'Цитата режиссёра',
        'content-manager.content-types.api::performance.performance.fields.designer': 'Художник',
        'content-manager.content-types.api::performance.performance.fields.lightingDesigner': 'Художник по свету',
        'content-manager.content-types.api::performance.performance.fields.soundDesigner': 'Звукорежиссёр',
        'content-manager.content-types.api::performance.performance.fields.lightSoundOperator': 'Свето-звукооператор',
        'content-manager.content-types.api::performance.performance.fields.invitedCast': 'Внешний состав (приглашённые)',
        'content-manager.content-types.api::performance.performance.fields.reviews': 'Отзывы',
        'content-manager.content-types.api::performance.performance.fields.teaserUrl': 'Ссылка на трейлер',
        'content-manager.content-types.api::performance.performance.fields.date': 'Дата',
        'content-manager.content-types.api::performance.performance.fields.time': 'Время',
        'content-manager.content-types.api::performance.performance.fields.ageRating': 'Возрастной рейтинг',
        'content-manager.content-types.api::performance.performance.fields.genre': 'Жанр',
        'content-manager.content-types.api::performance.performance.fields.description': 'Описание',
        'content-manager.content-types.api::performance.performance.fields.duration': 'Продолжительность',
        'content-manager.content-types.api::performance.performance.fields.intermissions': 'Количество антрактов',
        'content-manager.content-types.api::performance.performance.fields.isPremiere': 'Премьера',
        'content-manager.content-types.api::performance.performance.fields.inAfisha': 'В афише',
        'content-manager.content-types.api::performance.performance.fields.schedule': 'Расписание',
        'content-manager.content-types.api::performance.performance.fields.awards': 'Награды',
        'content-manager.content-types.api::performance.performance.fields.festivals': 'Фестивали',
        'content-manager.content-types.api::performance.performance.fields.ticketsUrl': 'Ссылка на билеты',

        // api::theater-gallery.theater-gallery — Фото галереи
        'content-manager.content-types.api::theater-gallery.theater-gallery.info.displayName': 'Фото галереи',
        'content-manager.content-types.api::theater-gallery.theater-gallery.fields.image': 'Изображение',
        'content-manager.content-types.api::theater-gallery.theater-gallery.fields.alt': 'Подпись (для доступности)',
        'content-manager.content-types.api::theater-gallery.theater-gallery.fields.order': 'Порядок',

        // api::teatr-teos.teatr-teos — Театр ТЕОС
        'content-manager.content-types.api::teatr-teos.teatr-teos.info.displayName': 'Театр ТЕОС',
        'content-type-builder.content-types.api::teatr-teos.teatr-teos.info.displayName': 'Театр ТЕОС',
        'content-manager.content-types.api::teatr-teos.teatr-teos.fields.title': 'Заголовок',
        'content-manager.content-types.api::teatr-teos.teatr-teos.fields.lead': 'Подзаголовок',
        'content-manager.content-types.api::teatr-teos.teatr-teos.fields.aboutText': 'О театре',
        'content-manager.content-types.api::teatr-teos.teatr-teos.fields.logo': 'Логотип театра',
        'content-manager.content-types.api::teatr-teos.teatr-teos.fields.address': 'Адрес',
        'content-manager.content-types.api::teatr-teos.teatr-teos.fields.howToGetThere': 'Как добраться',
        'content-manager.content-types.api::teatr-teos.teatr-teos.fields.phone': 'Телефон',
        'content-manager.content-types.api::teatr-teos.teatr-teos.fields.socialVk': 'ВКонтакте',
        'content-manager.content-types.api::teatr-teos.teatr-teos.fields.socialTelegram': 'Telegram',
        'content-manager.content-types.api::teatr-teos.teatr-teos.fields.partnerBlockText': 'Текст блока «Спектакли и билеты»',
        'content-manager.content-types.api::teatr-teos.teatr-teos.fields.partnerBlockLink': 'Ссылка на сайт партнёра',
        'content-manager.content-types.api::teatr-teos.teatr-teos.fields.partnerBlockButtonLabel': 'Текст кнопки перехода',

        // api::arenda-zala.arenda-zala — Аренда зала
        'content-manager.content-types.api::arenda-zala.arenda-zala.info.displayName': 'Аренда зала',
        'content-type-builder.content-types.api::arenda-zala.arenda-zala.info.displayName': 'Аренда зала',
        'content-manager.content-types.api::arenda-zala.arenda-zala.fields.title': 'Заголовок',
        'content-manager.content-types.api::arenda-zala.arenda-zala.fields.lead': 'Подзаголовок',
        'content-manager.content-types.api::arenda-zala.arenda-zala.fields.conditionsText': 'Условия аренды',
        'content-manager.content-types.api::arenda-zala.arenda-zala.fields.gallery': 'Фотогалерея',
        'content-manager.content-types.api::arenda-zala.arenda-zala.fields.howToBookText': 'Как забронировать',

        // api::pomoch-teatru.pomoch-teatru — Помочь театру
        'content-manager.content-types.api::pomoch-teatru.pomoch-teatru.info.displayName': 'Помочь театру',
        'content-type-builder.content-types.api::pomoch-teatru.pomoch-teatru.info.displayName': 'Помочь театру',
        'content-manager.content-types.api::pomoch-teatru.pomoch-teatru.fields.title': 'Заголовок',
        'content-manager.content-types.api::pomoch-teatru.pomoch-teatru.fields.lead': 'Подзаголовок',
        'content-manager.content-types.api::pomoch-teatru.pomoch-teatru.fields.requisitesText': 'Реквизиты',
        'content-manager.content-types.api::pomoch-teatru.pomoch-teatru.fields.qrCodeImage': 'QR-код',

        // api::partners.partners — Партнёры и спонсоры
        'content-manager.content-types.api::partners.partners.info.displayName': 'Партнёры и спонсоры',
        'content-type-builder.content-types.api::partners.partners.info.displayName': 'Партнёры и спонсоры',
        'content-manager.content-types.api::partners.partners.fields.title': 'Заголовок',
        'content-manager.content-types.api::partners.partners.fields.introText': 'Вступительный текст',
        'content-manager.content-types.api::partners.partners.fields.partners': 'Партнёры',

        // api::o-teatre.o-teatre — О театре
        'content-manager.content-types.api::o-teatre.o-teatre.info.displayName': 'О театре',
        'content-type-builder.content-types.api::o-teatre.o-teatre.info.displayName': 'О театре',
        'content-manager.content-types.api::o-teatre.o-teatre.fields.title': 'Заголовок',
        'content-manager.content-types.api::o-teatre.o-teatre.fields.lead': 'Подзаголовок',
        'content-manager.content-types.api::o-teatre.o-teatre.fields.historyText': 'История',
        'content-manager.content-types.api::o-teatre.o-teatre.fields.missionText': 'Миссия',
        'content-manager.content-types.api::o-teatre.o-teatre.fields.gallery': 'Галерея',

        // api::theater-review.theater-review — Отзыв о театре
        'content-manager.content-types.api::theater-review.theater-review.info.displayName': 'Отзывы о театре',
        'content-manager.content-types.api::theater-review.theater-review.fields.quote': 'Цитата',
        'content-manager.content-types.api::theater-review.theater-review.fields.author': 'Автор',
        'content-manager.content-types.api::theater-review.theater-review.fields.vkUrl': 'Ссылка ВКонтакте',
        'content-manager.content-types.api::theater-review.theater-review.fields.yandexMapsUrl': 'Ссылка в Яндекс Картах',
        'content-manager.content-types.api::theater-review.theater-review.fields.twoGisUrl': 'Ссылка в 2ГИС',
        'content-manager.content-types.api::theater-review.theater-review.fields.order': 'Порядок',

        // === Content-type Builder: Components ===
        'content-type-builder.components.shared.role-item': 'Роль в спектакле',
        'content-type-builder.components.shared.role-item.attributes.text': 'Текст роли',
        'content-type-builder.components.shared.role-item.attributes.performance': 'Спектакль',
        'content-type-builder.components.shared.cast-member': 'Приглашённый участник',
        'content-type-builder.components.shared.cast-member.attributes.name': 'Имя',
        'content-type-builder.components.shared.cast-member.attributes.role': 'Роль',
        'content-type-builder.components.shared.cast-member.attributes.photo': 'Фото',
        'content-type-builder.components.shared.schedule-item': 'Дата и время показа',
        'content-type-builder.components.shared.schedule-item.attributes.date': 'Дата',
        'content-type-builder.components.shared.schedule-item.attributes.time': 'Время',
        'content-type-builder.components.shared.review': 'Отзыв',
        'content-type-builder.components.shared.review.attributes.quote': 'Цитата',
        'content-type-builder.components.shared.review.attributes.author': 'Автор',
        'content-type-builder.components.shared.review.attributes.vkUrl': 'Ссылка ВКонтакте',
        'content-type-builder.components.shared.award': 'Награда',
        'content-type-builder.components.shared.award.attributes.title': 'Название',
        'content-type-builder.components.shared.award.attributes.year': 'Год',
        'content-type-builder.components.shared.festival': 'Фестиваль',
        'content-type-builder.components.shared.festival.attributes.title': 'Название',
        'content-type-builder.components.shared.festival.attributes.year': 'Год',
        'content-type-builder.components.shared.festival.attributes.place': 'Место',
        'content-type-builder.components.shared.festival.attributes.logo': 'Логотип',

        // Альтернативный формат для Content Manager (компоненты внутри контента)
        'content-manager.components.shared.role-item': 'Роль в спектакле',
        'content-manager.components.shared.role-item.attributes.text': 'Текст роли',
        'content-manager.components.shared.role-item.attributes.performance': 'Спектакль',
        'content-manager.components.shared.cast-member': 'Приглашённый участник',
        'content-manager.components.shared.cast-member.attributes.name': 'Имя',
        'content-manager.components.shared.cast-member.attributes.role': 'Роль',
        'content-manager.components.shared.cast-member.attributes.photo': 'Фото',
        'content-manager.components.shared.schedule-item': 'Дата и время показа',
        'content-manager.components.shared.schedule-item.attributes.date': 'Дата',
        'content-manager.components.shared.schedule-item.attributes.time': 'Время',
        'content-manager.components.shared.review': 'Отзыв',
        'content-manager.components.shared.review.attributes.quote': 'Цитата',
        'content-manager.components.shared.review.attributes.author': 'Автор',
        'content-manager.components.shared.review.attributes.vkUrl': 'Ссылка ВКонтакте',
        'content-manager.components.shared.award': 'Награда',
        'content-manager.components.shared.award.attributes.title': 'Название',
        'content-manager.components.shared.award.attributes.year': 'Год',
        'content-manager.components.shared.festival': 'Фестиваль',
        'content-manager.components.shared.festival.attributes.title': 'Название',
        'content-manager.components.shared.festival.attributes.year': 'Год',
        'content-manager.components.shared.festival.attributes.place': 'Место',
        'content-manager.components.shared.festival.attributes.logo': 'Логотип',
        'content-manager.components.shared.partner-item': 'Партнёр',
        'content-manager.components.shared.partner-item.attributes.name': 'Название',
        'content-manager.components.shared.partner-item.attributes.logo': 'Логотип',
        'content-manager.components.shared.partner-item.attributes.url': 'Ссылка',

        // content-type-builder: поля одиночных типов
        'content-type-builder.content-types.api::teatr-teos.teatr-teos.fields.title': 'Заголовок',
        'content-type-builder.content-types.api::teatr-teos.teatr-teos.fields.lead': 'Подзаголовок',
        'content-type-builder.content-types.api::teatr-teos.teatr-teos.fields.aboutText': 'О театре',
        'content-type-builder.content-types.api::teatr-teos.teatr-teos.fields.logo': 'Логотип театра',
        'content-type-builder.content-types.api::teatr-teos.teatr-teos.fields.address': 'Адрес',
        'content-type-builder.content-types.api::teatr-teos.teatr-teos.fields.howToGetThere': 'Как добраться',
        'content-type-builder.content-types.api::teatr-teos.teatr-teos.fields.phone': 'Телефон',
        'content-type-builder.content-types.api::teatr-teos.teatr-teos.fields.socialVk': 'ВКонтакте',
        'content-type-builder.content-types.api::teatr-teos.teatr-teos.fields.socialTelegram': 'Telegram',
        'content-type-builder.content-types.api::teatr-teos.teatr-teos.fields.partnerBlockText': 'Текст блока «Спектакли и билеты»',
        'content-type-builder.content-types.api::teatr-teos.teatr-teos.fields.partnerBlockLink': 'Ссылка на сайт партнёра',
        'content-type-builder.content-types.api::teatr-teos.teatr-teos.fields.partnerBlockButtonLabel': 'Текст кнопки перехода',

        'content-type-builder.content-types.api::arenda-zala.arenda-zala.fields.title': 'Заголовок',
        'content-type-builder.content-types.api::arenda-zala.arenda-zala.fields.lead': 'Подзаголовок',
        'content-type-builder.content-types.api::arenda-zala.arenda-zala.fields.conditionsText': 'Условия аренды',
        'content-type-builder.content-types.api::arenda-zala.arenda-zala.fields.gallery': 'Фотогалерея',
        'content-type-builder.content-types.api::arenda-zala.arenda-zala.fields.howToBookText': 'Как забронировать',

        // api::performance.performance — Content-type Builder
        'content-type-builder.content-types.api::performance.performance.fields.invitedCast': 'Внешний состав (приглашённые)',

        'content-type-builder.content-types.api::pomoch-teatru.pomoch-teatru.fields.title': 'Заголовок',
        'content-type-builder.content-types.api::pomoch-teatru.pomoch-teatru.fields.lead': 'Подзаголовок',
        'content-type-builder.content-types.api::pomoch-teatru.pomoch-teatru.fields.requisitesText': 'Реквизиты',
        'content-type-builder.content-types.api::pomoch-teatru.pomoch-teatru.fields.qrCodeImage': 'QR-код',

        'content-type-builder.content-types.api::partners.partners.fields.title': 'Заголовок',
        'content-type-builder.content-types.api::partners.partners.fields.introText': 'Вступительный текст',
        'content-type-builder.content-types.api::partners.partners.fields.partners': 'Партнёры',

        'content-type-builder.content-types.api::o-teatre.o-teatre.fields.title': 'Заголовок',
        'content-type-builder.content-types.api::o-teatre.o-teatre.fields.lead': 'Подзаголовок',
        'content-type-builder.content-types.api::o-teatre.o-teatre.fields.historyText': 'История',
        'content-type-builder.content-types.api::o-teatre.o-teatre.fields.missionText': 'Миссия',
        'content-type-builder.content-types.api::o-teatre.o-teatre.fields.gallery': 'Галерея',
      },
    },
  },
  bootstrap(_app: StrapiApp) {
    // app available for custom plugins
  },
};
